# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='quotes_name',
        ),
    ]
