# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_remove_quotes_quotes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_quotes',
            name='quotes_pics',
            field=models.ImageField(upload_to='quote'),
        ),
    ]
